# Generated by Django 5.0.7 on 2024-07-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_book_authr_book_is_best_selling_alter_book_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authr',
            new_name='author',
        ),
    ]
